# ----------------------------
# Faster R-CNN Model-Specific Configuration
# ----------------------------

identifier: "faster_rcnn"          # Model name identifier (used for selecting this configuration)
backbone: "resnet50"               # Backbone architecture (options: ['resnet50', 'resnet101', 'mobilenet_v2'])
pretrained: true                   # Load a model pre-trained on COCO dataset
num_classes: 91                    # Number of output classes (including background)
min_size: 800                      # Minimum size of the input image
max_size: 1333                     # Maximum size of the input image
nms_threshold: 0.3                 # IoU threshold for Non-Maximum Suppression (NMS)
box_score_threshold: 0.05          # Minimum score threshold for valid detections


# ----------------------------
# Training Configuration for Faster R-CNN
# ----------------------------
train:
  epoch: 50                          # Number of training epochs
  batch_size: 8                      # Number of samples per batch
  optimizer: SGD                      # Optimization algorithm (options: ['SGD', 'Adam'])
  lr: 0.005                          # Initial learning rate
  momentum: 0.9                       # Momentum factor (for SGD optimizer)
  weight_decay: 0.0005                # Weight decay (L2 regularization)
  freeze_layers: 0                    # Number of backbone layers to freeze during training

  # ----------------------------
  # Learning Rate Scheduler Configuration
  # ----------------------------
  scheduler:
    type: StepLR                      # Learning rate scheduler type (options: ['StepLR', 'ReduceLROnPlateau', 'OneCycleLR'])
    step_size: 10                      # Number of epochs between learning rate reductions
    gamma: 0.1                         # Factor by which learning rate is reduced (StepLR)
    patience: 3                        # Patience for ReduceLROnPlateau
