# ----------------------------
# YOLO Model-Specific Configuration
# ----------------------------
identifier: yolo                  # Model name identifier (used for selecting this configuration)
weights: yolo11m.pt               # Pretrained weights file (default: 'yolo11m.pt')
img_size: 640                     # Input image size for the model (typically 416, 512, or 640)

conf_threshold: 0.25              # Confidence threshold for filtering weak detections
iou_threshold: 0.45               # Intersection over Union (IoU) threshold for Non-Maximum Suppression (NMS)
freeze_layers: 0                  # Number of backbone layers to freeze during training
