# ----------------------------
# Dataset Configuration
# ----------------------------
data:
  folder: coco8                    # Name of the dataset folder (relative to dataset_root_dir)
  single_class: true               # If true, treats the dataset as a single-class detection task

  # Dataset Splitting
  split_ratios: [0.8, 0.2, 0.0]    # Ratios for train, validation, and test splits (should sum to 1.0)
  split_code: null                 # Custom split identifier (e.g., to reference a specific split configuration)
  test_split: val                  # Partition to be used for evaluation: ['val', 'test']

  # Cross-Validation Settings
  num_folds: 3                     # Number of folds for cross-validation
  use_replacement: false           # Whether to use replacement in cross-validation sampling

  # Data Augmentation Settings
  use_augmentation: false          # If true, applies data augmentation techniques during training
