# Config composition
defaults:
  - _self_
  - model: yolo
  - experiment
  - override hydra/job_logging: disabled  
  - override hydra/hydra_logging: disabled


# ----------------------------
# Model Configuration
# ----------------------------
model: 
  saved_model_folder: null        # Save folder name for a previously trained model (set dynamically)


# ----------------------------
# Experiment Configuration
# ----------------------------
exp:
  seed: 42                          # Random seed for reproducibility
  device: cuda                      # Computing device: ['cpu', 'mps', 'cuda']
  on_server: false                  # Whether the script is running on a server
  mode: train                       # Running mode: ['train', 'crossval', 'test', 'predict']

  number: 0                         # Experiment number for tracking different runs
  name: default                     # Experiment name for logging and model saving
  save_name: null                   # Custom name used for saving model/prediction files - set dynamically


# ----------------------------
# Paths Configuration
# ----------------------------
path:
  project_root_dir: '/Volumes/Works/Projects/SOTA-Detection-Lab'  # Absolute path to the project directory - set dynamically for server
  
  dataset_root_dir:                         # Dataset location (relative to project_root_dir) - set dynamically
    local: './data/processed'               # Local dataset folder inside the project directory
    server: '../datasets/object_detection'  # Dataset location on the server (one directory above project)

  input_dir: experiments/input              # Directory for input experiment files
  output_dir: experiments/output/${model.identifier}  # Directory for model-specific outputs
  custom_splits_dir: ${path.input_dir}/custom_splits  # Directory for custom dataset splits
  
  predict_image_folder: null                # Folder containing images for prediction


# ----------------------------
# Hydra Configuration
# ----------------------------
hydra:
  run:
    dir: .              # Run Hydra in the current working directory
  output_subdir: null   # Prevent Hydra from creating an additional output directory
  job:
    chdir: false        # Prevent changing the working directory within Hydra
